"""
Tests for the HTML report builder (html_report.py).

These tests validate HTML report generation from ScenarioResult objects.
They do not require Windows or any external tools.
"""

from __future__ import annotations

from pathlib import Path

from launch_lab.html_report import (
    _bool_display,
    _esc,
    _exit_badge,
    _render_html_report,
    build_html_report,
)
from launch_lab.expectations import check_expectations
from launch_lab.models import LauncherKind, ScenarioResult, Subsystem


def _render(results: list[ScenarioResult]) -> str:
    """Helper that wraps _render_html_report with default anomaly_map/ai_summary."""
    anomaly_map = {r.scenario_id: check_expectations(r) for r in results}
    return _render_html_report(results, anomaly_map, None)


def _make_result(**kwargs) -> ScenarioResult:
    defaults = dict(
        scenario_id="test-scenario",
        platform="win32",
        python_version="3.12.0",
        launcher=LauncherKind.PYTHON,
        mode="script.py",
        fixture="raw_py",
    )
    defaults.update(kwargs)
    return ScenarioResult(**defaults)


def test_build_html_report_returns_none_when_no_results(tmp_path: Path):
    empty_json = tmp_path / "json"
    empty_json.mkdir()
    result = build_html_report(json_dir=empty_json, output_dir=tmp_path / "out")
    assert result is None


def test_build_html_report_writes_file(tmp_path: Path):
    json_dir = tmp_path / "json"
    json_dir.mkdir()
    r = _make_result(exit_code=0)
    (json_dir / "test-scenario.json").write_text(r.model_dump_json(indent=2), encoding="utf-8")
    dest = build_html_report(json_dir=json_dir, output_dir=tmp_path / "out")
    assert dest is not None
    assert dest.exists()
    assert dest.name == "report.html"
    content = dest.read_text(encoding="utf-8")
    assert "<!DOCTYPE html>" in content
    assert "test-scenario" in content


def test_html_report_contains_summary_cards():
    results = [
        _make_result(scenario_id="s1", exit_code=0),
        _make_result(scenario_id="s2", exit_code=1),
        _make_result(scenario_id="s3", exit_code=None),
    ]
    html = _render(results)
    assert "Total Scenarios" in html
    assert "Passed (exit 0)" in html
    assert "Failed" in html
    assert "Unknown" in html


def test_html_report_contains_all_scenarios_table():
    results = [_make_result(scenario_id="alpha", exit_code=0)]
    html = _render(results)
    assert "All Scenarios" in html
    assert "alpha" in html


def test_html_report_unified_table_with_launchers():
    """The report should show all launchers in a single unified table."""
    results = [
        _make_result(scenario_id="s1", launcher=LauncherKind.PYTHON, exit_code=0),
        _make_result(scenario_id="s2", launcher=LauncherKind.UV, exit_code=0),
    ]
    html = _render(results)
    assert "python" in html
    assert "uv" in html
    # The old per-launcher sections should be gone
    assert "Results by Launcher" not in html


def test_html_report_exit_badges():
    results = [
        _make_result(scenario_id="pass", exit_code=0),
        _make_result(scenario_id="fail", exit_code=1),
        _make_result(scenario_id="unknown", exit_code=None),
    ]
    html = _render(results)
    assert "badge-pass" in html
    assert "badge-fail" in html
    assert "badge-na" in html


def test_html_report_has_pe_subsystem():
    results = [
        _make_result(
            scenario_id="pe-test",
            exit_code=0,
            pe_subsystem=Subsystem.CUI,
        )
    ]
    html = _render(results)
    assert "CUI" in html


def test_esc_helper():
    assert _esc(None) == "N/A"
    assert _esc("hello") == "hello"
    assert _esc("<script>") == "&lt;script&gt;"
    assert _esc(42) == "42"


def test_exit_badge_helper():
    assert "badge-pass" in _exit_badge(0)
    assert "badge-fail" in _exit_badge(1)
    assert "badge-na" in _exit_badge(None)


def test_bool_display_helper():
    assert _bool_display(True) == "Yes"
    assert _bool_display(False) == "No"
    assert _bool_display(None) == "N/A"


def test_html_report_contains_footer():
    results = [_make_result(exit_code=0)]
    html = _render(results)
    assert "Report generated by py-launch-lab" in html


def test_html_report_is_self_contained():
    """The HTML report should have embedded CSS and JS (no external references)."""
    results = [_make_result(exit_code=0)]
    html = _render(results)
    assert "<style>" in html
    assert "<script>" in html
    assert "stylesheet" not in html.lower()
    assert "<link rel=" not in html.lower()
    assert "<script src=" not in html.lower()


def test_html_report_includes_os_version():
    results = [_make_result(exit_code=0, os_version="Windows-10-10.0.22631-SP0")]
    html = _render(results)
    assert "Windows-10-10.0.22631-SP0" in html
    assert "OS:" in html


def test_html_report_includes_python_version():
    results = [_make_result(exit_code=0, python_version="3.12.3")]
    html = _render(results)
    assert "Python:" in html
    assert "3.12.3" in html


def test_html_report_includes_uv_version():
    results = [_make_result(exit_code=0, uv_version="uv 0.7.12")]
    html = _render(results)
    assert "uv:" in html
    assert "uv 0.7.12" in html


def test_html_report_anomaly_highlighting():
    """Rows with anomalies should be highlighted with an explanation bubble."""
    results = [
        _make_result(
            scenario_id="venv-pythonw-script-py",
            launcher=LauncherKind.VENV_DIRECT,
            exit_code=0,
            pe_subsystem=Subsystem.CUI,
            console_window_detected=True,
        ),
    ]
    html = _render(results)
    assert "anomaly-row" in html
    assert "anomaly-bubble" in html
    assert "Unexpected behaviour detected" in html


def test_html_report_column_filters():
    """The unified table should have filter dropdowns and text inputs."""
    results = [_make_result(exit_code=0)]
    html = _render(results)
    assert "filter-row" in html
    assert "<select>" in html
    assert 'placeholder="Filter' in html


def test_html_report_uv_version_column():
    """The unified table should include a uv Version column."""
    results = [_make_result(exit_code=0, uv_version="uv 0.5.0")]
    html = _render(results)
    assert "uv Version" in html
    assert "uv 0.5.0" in html


def test_html_report_uv_version_filter():
    """The uv Version column should have a filter dropdown."""
    results = [
        _make_result(scenario_id="s1", exit_code=0, uv_version="uv 0.5.0"),
        _make_result(scenario_id="s2", exit_code=0, uv_version="uv 0.6.0"),
    ]
    html = _render(results)
    # Both versions should appear as filter options
    assert "uv 0.5.0" in html
    assert "uv 0.6.0" in html


def test_html_report_multi_version_both_shown():
    """Results from multiple uv versions should all appear in the same table."""
    results = [
        _make_result(scenario_id="python-script-py", exit_code=0, uv_version="uv 0.5.0",
                     uv_version_hash="aaa1111111"),
        _make_result(scenario_id="python-script-py", exit_code=0, uv_version="uv 0.6.0",
                     uv_version_hash="bbb2222222"),
    ]
    html = _render(results)
    # Both version rows should appear
    assert "uv 0.5.0" in html
    assert "uv 0.6.0" in html
    # The scenario id should appear twice
    assert html.count("python-script-py") >= 2


def test_artifact_filename_with_hash():
    """artifact_filename should include the version hash when present."""
    from launch_lab.collect import artifact_filename

    r = _make_result(uv_version_hash="abc1234567")
    name = artifact_filename(r)
    assert name == "test-scenario__abc1234567.json"


def test_artifact_filename_without_hash():
    """artifact_filename should fall back to legacy naming when no hash."""
    from launch_lab.collect import artifact_filename

    r = _make_result()
    name = artifact_filename(r)
    assert name == "test-scenario.json"


def test_save_result_creates_versioned_file(tmp_path: Path):
    """save_result should use versioned filename when uv_version_hash is set."""
    from launch_lab.collect import save_result

    r = _make_result(uv_version="uv 0.5.0", uv_version_hash="abc1234567")
    dest = save_result(r, output_dir=tmp_path)
    assert dest.name == "test-scenario__abc1234567.json"
    assert dest.exists()


def test_save_result_creates_legacy_file_without_hash(tmp_path: Path):
    """save_result should use legacy naming when no uv_version_hash."""
    from launch_lab.collect import save_result

    r = _make_result()
    dest = save_result(r, output_dir=tmp_path)
    assert dest.name == "test-scenario.json"
    assert dest.exists()


def test_load_all_results_multi_version(tmp_path: Path):
    """load_all_results should load all versioned files from a directory."""
    from launch_lab.collect import load_all_results, save_result

    r1 = _make_result(scenario_id="s1", uv_version="uv 0.5.0", uv_version_hash="aaa1111111")
    r2 = _make_result(scenario_id="s1", uv_version="uv 0.6.0", uv_version_hash="bbb2222222")
    save_result(r1, output_dir=tmp_path)
    save_result(r2, output_dir=tmp_path)
    results = load_all_results(tmp_path)
    assert len(results) == 2
    versions = {r.uv_version for r in results}
    assert versions == {"uv 0.5.0", "uv 0.6.0"}
