"""
Tests for the HTML report builder (html_report.py).

These tests validate HTML report generation from ScenarioResult objects.
They do not require Windows or any external tools.
"""

from __future__ import annotations

from pathlib import Path

from launch_lab.html_report import (
    _bool_display,
    _esc,
    _exit_badge,
    _render_html_report,
    build_html_report,
)
from launch_lab.models import LauncherKind, ScenarioResult, Subsystem


def _make_result(**kwargs) -> ScenarioResult:
    defaults = dict(
        scenario_id="test-scenario",
        platform="win32",
        python_version="3.12.0",
        launcher=LauncherKind.PYTHON,
        mode="script.py",
        fixture="raw_py",
    )
    defaults.update(kwargs)
    return ScenarioResult(**defaults)


def test_build_html_report_returns_none_when_no_results(tmp_path: Path):
    empty_json = tmp_path / "json"
    empty_json.mkdir()
    result = build_html_report(json_dir=empty_json, output_dir=tmp_path / "out")
    assert result is None


def test_build_html_report_writes_file(tmp_path: Path):
    json_dir = tmp_path / "json"
    json_dir.mkdir()
    r = _make_result(exit_code=0)
    (json_dir / "test-scenario.json").write_text(r.model_dump_json(indent=2), encoding="utf-8")
    dest = build_html_report(json_dir=json_dir, output_dir=tmp_path / "out")
    assert dest is not None
    assert dest.exists()
    assert dest.name == "report.html"
    content = dest.read_text(encoding="utf-8")
    assert "<!DOCTYPE html>" in content
    assert "test-scenario" in content


def test_html_report_contains_summary_cards():
    results = [
        _make_result(scenario_id="s1", exit_code=0),
        _make_result(scenario_id="s2", exit_code=1),
        _make_result(scenario_id="s3", exit_code=None),
    ]
    html = _render_html_report(results)
    assert "Total Scenarios" in html
    assert "Passed (exit 0)" in html
    assert "Failed" in html
    assert "Unknown" in html


def test_html_report_contains_all_scenarios_table():
    results = [_make_result(scenario_id="alpha", exit_code=0)]
    html = _render_html_report(results)
    assert "All Scenarios" in html
    assert "alpha" in html


def test_html_report_per_launcher_sections():
    results = [
        _make_result(scenario_id="s1", launcher=LauncherKind.PYTHON, exit_code=0),
        _make_result(scenario_id="s2", launcher=LauncherKind.UV, exit_code=0),
    ]
    html = _render_html_report(results)
    assert "python" in html
    assert "uv" in html
    assert "Results by Launcher" in html


def test_html_report_exit_badges():
    results = [
        _make_result(scenario_id="pass", exit_code=0),
        _make_result(scenario_id="fail", exit_code=1),
        _make_result(scenario_id="unknown", exit_code=None),
    ]
    html = _render_html_report(results)
    assert "badge-pass" in html
    assert "badge-fail" in html
    assert "badge-na" in html


def test_html_report_has_pe_subsystem():
    results = [
        _make_result(
            scenario_id="pe-test",
            exit_code=0,
            pe_subsystem=Subsystem.CUI,
        )
    ]
    html = _render_html_report(results)
    assert "CUI" in html


def test_esc_helper():
    assert _esc(None) == "N/A"
    assert _esc("hello") == "hello"
    assert _esc("<script>") == "&lt;script&gt;"
    assert _esc(42) == "42"


def test_exit_badge_helper():
    assert "badge-pass" in _exit_badge(0)
    assert "badge-fail" in _exit_badge(1)
    assert "badge-na" in _exit_badge(None)


def test_bool_display_helper():
    assert _bool_display(True) == "Yes"
    assert _bool_display(False) == "No"
    assert _bool_display(None) == "N/A"


def test_html_report_contains_footer():
    results = [_make_result(exit_code=0)]
    html = _render_html_report(results)
    assert "Report generated by py-launch-lab" in html


def test_html_report_is_self_contained():
    """The HTML report should have embedded CSS (no external references)."""
    results = [_make_result(exit_code=0)]
    html = _render_html_report(results)
    assert "<style>" in html
    assert "stylesheet" not in html.lower()
    assert "<link rel=" not in html.lower()
    assert "<script src=" not in html.lower()


def test_html_report_includes_os_version():
    results = [_make_result(exit_code=0, os_version="Windows-10-10.0.22631-SP0")]
    html = _render_html_report(results)
    assert "Windows-10-10.0.22631-SP0" in html
    assert "OS:" in html


def test_html_report_includes_python_version():
    results = [_make_result(exit_code=0, python_version="3.12.3")]
    html = _render_html_report(results)
    assert "Python:" in html
    assert "3.12.3" in html


def test_html_report_includes_uv_version():
    results = [_make_result(exit_code=0, uv_version="uv 0.7.12")]
    html = _render_html_report(results)
    assert "uv:" in html
    assert "uv 0.7.12" in html
