"""
Tests for the report builder (report.py).

These tests validate Markdown report generation from ScenarioResult objects.
They do not require Windows or any external tools.
"""

from __future__ import annotations

from pathlib import Path

from launch_lab.models import LauncherKind, ScenarioResult, Subsystem
from launch_lab.report import _na, _render_report, build_report


def _make_result(**kwargs) -> ScenarioResult:
    defaults = dict(
        scenario_id="test-scenario",
        platform="win32",
        python_version="3.12.0",
        launcher=LauncherKind.PYTHON,
        mode="script.py",
        fixture="raw_py",
    )
    defaults.update(kwargs)
    return ScenarioResult(**defaults)


def test_build_report_returns_none_when_no_results(tmp_path: Path):
    empty_json = tmp_path / "json"
    empty_json.mkdir()
    result = build_report(json_dir=empty_json, output_dir=tmp_path / "out")
    assert result is None


def test_build_report_writes_file(tmp_path: Path):
    json_dir = tmp_path / "json"
    json_dir.mkdir()
    r = _make_result(exit_code=0)
    (json_dir / "test-scenario.json").write_text(
        r.model_dump_json(indent=2), encoding="utf-8"
    )
    dest = build_report(json_dir=json_dir, output_dir=tmp_path / "out")
    assert dest is not None
    assert dest.exists()
    content = dest.read_text(encoding="utf-8")
    assert "# Python Launch Lab" in content
    assert "test-scenario" in content


def test_build_report_writes_findings(tmp_path: Path):
    json_dir = tmp_path / "json"
    json_dir.mkdir()
    r = _make_result(exit_code=0)
    (json_dir / "test-scenario.json").write_text(
        r.model_dump_json(indent=2), encoding="utf-8"
    )
    findings = tmp_path / "findings"
    dest = build_report(
        json_dir=json_dir,
        output_dir=tmp_path / "out",
        findings_dir=findings,
    )
    assert dest is not None
    findings_report = findings / "report.md"
    assert findings_report.exists()
    assert findings_report.read_text(encoding="utf-8") == dest.read_text(encoding="utf-8")


def test_render_report_contains_summary():
    results = [
        _make_result(scenario_id="s1", exit_code=0),
        _make_result(scenario_id="s2", exit_code=1),
    ]
    lines = _render_report(results)
    text = "\n".join(lines)
    assert "**Total scenarios:** 2" in text
    assert "**Passed (exit 0):** 1" in text
    assert "**Failed (exit ≠ 0):** 1" in text


def test_render_report_contains_all_scenarios_table():
    results = [_make_result(scenario_id="alpha", exit_code=0)]
    lines = _render_report(results)
    text = "\n".join(lines)
    assert "## All Scenarios" in text
    assert "alpha" in text


def test_render_report_per_launcher_section():
    results = [
        _make_result(scenario_id="s1", launcher=LauncherKind.PYTHON, exit_code=0),
        _make_result(scenario_id="s2", launcher=LauncherKind.UV, exit_code=0),
    ]
    lines = _render_report(results)
    text = "\n".join(lines)
    assert "### Launcher: `python`" in text
    assert "### Launcher: `uv`" in text


def test_render_report_footer():
    results = [_make_result(exit_code=0)]
    lines = _render_report(results)
    text = "\n".join(lines)
    assert "Report generated by py-launch-lab" in text


def test_na_helper():
    assert _na(None) == "—"
    assert _na(True) == "True"
    assert _na("CUI") == "CUI"
    assert _na(0) == "0"


def test_render_report_with_pe_subsystem():
    results = [
        _make_result(
            scenario_id="pe-test",
            exit_code=0,
            pe_subsystem=Subsystem.CUI,
            console_window_detected=True,
            visible_window_detected=False,
        )
    ]
    lines = _render_report(results)
    text = "\n".join(lines)
    assert "CUI" in text
    assert "pe-test" in text


def test_render_report_none_exit_code():
    results = [_make_result(scenario_id="no-exit", exit_code=None)]
    lines = _render_report(results)
    text = "\n".join(lines)
    assert "**Unknown (no exit code):** 1" in text
    # In the table, None exit code renders as "—"
    assert "—" in text
